;;; nightcity-mix-theme.el --- Night City Mix  -*- lexical-binding: t -*-
;; Palette: themes/night-city-palettes/palettes/night-city-mix.json
;; (Box UK × Solarized Osaka × Lucy). Same colours as nightcity.nvim "mix".
;;; Code:

(deftheme nightcity-mix "Night City Mix — cyan/teal on #101a1f.")

(let ((bg "#101a1f") (bg-dark "#0c1217") (bg-hl "#15242d") (surface "#1d2c36") (overlay "#2c3d4b")
      (fg "#b6c5d3") (dim "#5b7189") (soft "#dce2e8")
      (cyan "#2bbcd5") (azure "#2ba3c9") (teal "#0cc7c2") (green "#49d575") (yellow "#f2c74b")
      (apricot "#ffa066") (coral "#f37c4b") (pink "#f95b95") (purple "#be59d6")
      (magenta "#ff45d4") (blue "#4486d5") (red "#f65162"))
  (custom-theme-set-faces
   'nightcity-mix
   `(default ((t (:background ,bg :foreground ,fg))))
   `(cursor ((t (:background ,teal))))
   `(region ((t (:background ,overlay))))
   `(highlight ((t (:background ,bg-hl))))
   `(hl-line ((t (:background ,bg-hl))))
   `(fringe ((t (:background ,bg))))
   `(vertical-border ((t (:foreground ,surface))))
   `(window-divider ((t (:foreground ,surface))))
   `(window-divider-first-pixel ((t (:foreground ,surface))))
   `(window-divider-last-pixel ((t (:foreground ,surface))))
   `(line-number ((t (:foreground ,dim :background ,bg))))
   `(line-number-current-line ((t (:foreground ,yellow :background ,bg-hl :weight bold))))
   `(minibuffer-prompt ((t (:foreground ,cyan :weight bold))))
   `(link ((t (:foreground ,teal :underline t))))
   `(shadow ((t (:foreground ,dim))))
   `(error ((t (:foreground ,red)))) `(warning ((t (:foreground ,yellow)))) `(success ((t (:foreground ,green))))
   `(match ((t (:background ,surface :foreground ,yellow))))
   `(isearch ((t (:background ,yellow :foreground ,bg))))
   `(lazy-highlight ((t (:background ,overlay))))
   `(show-paren-match ((t (:foreground ,magenta :weight bold :underline t))))
   `(trailing-whitespace ((t (:background ,red))))
   ;; syntax
   `(font-lock-comment-face ((t (:foreground ,dim :slant italic))))
   `(font-lock-doc-face ((t (:foreground ,dim))))
   `(font-lock-string-face ((t (:foreground ,green))))
   `(font-lock-keyword-face ((t (:foreground ,purple))))
   `(font-lock-builtin-face ((t (:foreground ,azure))))
   `(font-lock-function-name-face ((t (:foreground ,cyan))))
   `(font-lock-function-call-face ((t (:foreground ,cyan))))
   `(font-lock-variable-name-face ((t (:foreground ,fg))))
   `(font-lock-type-face ((t (:foreground ,teal))))
   `(font-lock-constant-face ((t (:foreground ,apricot))))
   `(font-lock-number-face ((t (:foreground ,apricot))))
   `(font-lock-operator-face ((t (:foreground ,coral))))
   `(font-lock-property-name-face ((t (:foreground ,blue))))
   `(font-lock-preprocessor-face ((t (:foreground ,pink))))
   `(font-lock-warning-face ((t (:foreground ,yellow :weight bold))))
   ;; mode line
   `(mode-line ((t (:background ,surface :foreground ,fg :box nil))))
   `(mode-line-inactive ((t (:background ,bg-dark :foreground ,dim :box nil))))
   `(doom-modeline-bar ((t (:background ,cyan))))
   `(doom-modeline-evil-normal-state ((t (:foreground ,cyan))))
   `(doom-modeline-evil-insert-state ((t (:foreground ,green))))
   `(doom-modeline-evil-visual-state ((t (:foreground ,purple))))
   ;; completion
   `(vertico-current ((t (:background ,surface))))
   `(orderless-match-face-0 ((t (:foreground ,cyan :weight bold))))
   `(orderless-match-face-1 ((t (:foreground ,pink :weight bold))))
   `(orderless-match-face-2 ((t (:foreground ,yellow :weight bold))))
   `(orderless-match-face-3 ((t (:foreground ,green :weight bold))))
   `(corfu-default ((t (:background ,bg-dark :foreground ,fg))))
   `(corfu-current ((t (:background ,surface))))
   `(corfu-border ((t (:background ,overlay))))
   `(marginalia-documentation ((t (:foreground ,dim))))
   ;; diagnostics / git
   `(flymake-error ((t (:underline (:style wave :color ,red)))))
   `(flymake-warning ((t (:underline (:style wave :color ,yellow)))))
   `(flymake-note ((t (:underline (:style wave :color ,teal)))))
   `(diff-hl-insert ((t (:background ,green :foreground ,green))))
   `(diff-hl-change ((t (:background ,blue :foreground ,blue))))
   `(diff-hl-delete ((t (:background ,red :foreground ,red))))
   `(magit-section-highlight ((t (:background ,bg-hl))))
   `(magit-diff-hunk-heading ((t (:background ,surface :foreground ,fg))))
   `(magit-diff-hunk-heading-highlight ((t (:background ,overlay :foreground ,soft))))
   `(magit-diff-added ((t (:foreground ,green))))
   `(magit-diff-added-highlight ((t (:foreground ,green :background ,bg-hl))))
   `(magit-diff-removed ((t (:foreground ,red))))
   `(magit-diff-removed-highlight ((t (:foreground ,red :background ,bg-hl))))
   `(magit-branch-local ((t (:foreground ,cyan))))
   `(magit-branch-remote ((t (:foreground ,green))))
   ;; ui
   `(dashboard-banner ((t (:foreground ,teal))))
   `(dashboard-text-banner ((t (:foreground ,teal))))
   `(dashboard-heading ((t (:foreground ,cyan :weight bold))))
   `(dashboard-items-face ((t (:foreground ,fg))))
   `(dashboard-navigator ((t (:foreground ,yellow))))
   `(treemacs-root-face ((t (:foreground ,cyan :weight bold :height 1.1))))
   `(treemacs-directory-face ((t (:foreground ,azure))))
   `(treemacs-git-modified-face ((t (:foreground ,yellow))))
   `(treemacs-git-untracked-face ((t (:foreground ,green))))
   `(hl-todo ((t (:foreground ,magenta :weight bold))))
   `(which-key-key-face ((t (:foreground ,yellow))))
   `(which-key-group-description-face ((t (:foreground ,purple))))
   `(which-key-command-description-face ((t (:foreground ,fg))))
   ;; terminal (ansi from the palette)
   `(eat-term-color-0 ((t (:foreground "#0d151d")))) `(eat-term-color-8 ((t (:foreground "#2b3851"))))
   `(eat-term-color-1 ((t (:foreground ,red)))) `(eat-term-color-9 ((t (:foreground "#fa70a7"))))
   `(eat-term-color-2 ((t (:foreground ,green)))) `(eat-term-color-10 ((t (:foreground "#4deda4"))))
   `(eat-term-color-3 ((t (:foreground ,yellow)))) `(eat-term-color-11 ((t (:foreground "#f9dc6d"))))
   `(eat-term-color-4 ((t (:foreground ,blue)))) `(eat-term-color-12 ((t (:foreground "#6fa1ec"))))
   `(eat-term-color-5 ((t (:foreground "#e446bc")))) `(eat-term-color-13 ((t (:foreground "#ed7dde"))))
   `(eat-term-color-6 ((t (:foreground "#2dcad8")))) `(eat-term-color-14 ((t (:foreground "#5bf4f1"))))
   `(eat-term-color-7 ((t (:foreground "#b8c6d7")))) `(eat-term-color-15 ((t (:foreground "#e2e9f4"))))))

(provide-theme 'nightcity-mix)
;;; nightcity-mix-theme.el ends here
